Cliente/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     
     path('', Cliente_list.as_view(), name='Cliente_list'),
     path('create', Cliente_create.as_view(), name='Cliente_create'),
     path('edit/<int:pk>', Cliente_edit.as_view(), name='Cliente_edit'),
     path('delete/<int:pk>', Cliente_delete.as_view(), name='Cliente_delete'),

     path('sem-permissao/', sem_permissao, name='sem_permissao'),

     # path('api_request/', api_request_view, name='api_request'),
] 

integra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produtos.urls')),
    path('clientes/', include('Cliente.urls')),
    path('funcionario/', include('Funcionario.urls')),
    path('fornecedor/', include('Fornecedor.urls')),
    path('configuracao/', include('configuracao.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

produtos/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     
     path('', dashboard, name='dashboard'),

     path('produtos/', produto_list, name='lista_produtos'),
     path('produto/create', produto_create, name='produto_create'),
     path('produto/edit/<int:pk>', produto_edit, name='produto_edit'),
     path('produto/delete/<int:pk>', produto_delete, name='produto_delete'),
     
     path('categorias/', Categoria_list, name='Categoria_list'),
     path('categoria/create', Categoria_create, name='Categoria_create'),
     path('categoria/edit/<int:pk>', Categoria_edit, name='Categoria_edit'),
     path('categoria/delete/<int:pk>', Categoria_delete, name='Categoria_delete'),

     path('promocao/', Promocao_list, name='Promocao_list'),
     path('promocao/create', Promocao_create, name='Promocao_create'),
     path('promocao/edit/<int:pk>', Promocao_edit, name='Promocao_edit'),
     path('promocao/delete/<int:pk>', Promocao_delete, name='Promocao_delete'),

     path('unidades/', Unidade_list, name='Unidade_list'),
     path('unidade/create', Unidade_create, name='Unidade_create'),
     path('unidade/edit/<int:pk>', Unidade_edit, name='Unidade_edit'),
     path('unidade/delete/<int:pk>', Unidade_delete, name='Unidade_delete'),

     path('Marca_list/', Marca_list, name='Marca_list'),
     path('Marca/create', Marca_create, name='Marca_create'),
     path('Marca/edit/<int:pk>', Marca_edit, name='Marca_edit'),
     path('Marca/delete/<int:pk>', Marca_delete, name='Marca_delete'),

     # path('Fornecedor/', Fornecedor_list, name='Fornecedor_list'),
     # path('Fornecedor/create', Fornecedor_create, name='Fornecedor_create'),
     # path('Fornecedor/edit/<int:pk>', Fornecedor_edit, name='Fornecedor_edit'),
     # path('Fornecedor/delete/<int:pk>', Fornecedor_delete, name='Fornecedor_delete'),

     # path('Funcionario/', Funcionario_list, name='Funcionario_list'),
     # path('Funcionario/create', Funcionario_create, name='Funcionario_create'),
     # path('Funcionario/edit/<int:pk>', Funcionario_edit, name='Funcionario_edit'),
     # path('Funcionario/delete/<int:pk>', Funcionario_delete, name='Funcionario_delete'),

     path('Localizacao/', Localizacao_list, name='Localizacao_list'),
     path('Localizacao/create', Localizacao_create, name='Localizacao_create'),
     path('Localizacao/edit/<int:pk>', Localizacao_edit, name='Localizacao_edit'),
     path('Localizacao/delete/<int:pk>', Localizacao_delete, name='Localizacao_delete'),

     path('ordem_compra/', ordem_compra_list, name='ordem_compra_list'),
     path('ordem_compra/adicionar/', adicionar_ordem_compra, name='adicionar_ordem_compra'),
     path('ordem_compra/adicionar/<int:extra>/', adicionar_ordem_compra, name='adicionar_ordem_compraExtra'),
     path('ordem_compra/editar/<int:pk>/', editar_ordem_compra, name='editar_ordem_compra'),
     path('ordem_compra/editar/extra/<int:pk>/<int:extra>/', editar_ordem_compra, name='editar_ordem_compraExtra'),
     path('ordem_compra/item/deletar/<int:pk>/', deletar_itemordem_compra, name='deletar_itemordem_compra'),
     path('ordem_compra/deletar/<int:pk>/', deletar_ordem_compra, name='deletar_ordem_compra'),

     path('ordem_venda/', ordem_venda_list, name='ordem_venda_list'),
     path('ordem_venda/adicionar/', adicionar_ordem_venda, name='adicionar_ordem_venda'),
     path('ordem_venda/adicionar/<int:extra>/', adicionar_ordem_venda, name='adicionar_ordem_vendaExtra'),
     path('ordem_venda/editar/<int:pk>/', editar_ordem_venda, name='editar_ordem_venda'),
     path('ordem_venda/editar/extra/<int:pk>/<int:extra>/', editar_ordem_venda, name='editar_ordem_vendaExtra'),
     path('ordem_venda/item/deletar/<int:pk>/', deletar_itemordem_venda, name='deletar_itemordem_venda'),
     path('ordem_venda/deletar/<int:pk>/', deletar_ordem_venda, name='deletar_ordem_venda'),

     path('notas/', home_notas, name='home_notas'),
     path('notas/nfe/', home_nfe, name='home_nfe'),
     path('nfe/emitir', emitir_nota, name='emitir_nota'),
     path('nfe/cancelamento', cancelar_nota, name='cancelar_nota'),
     path('nfe/cce', correcao_nota, name='correcao_nota'),
     path('nfe/cce/status', consultar_correcao_status_nota, name='consultar_correcao_status_nota'),
     path('nfe/resumoporid', resumo_nota, name='resumo_nota'),
     path('nfe/resumoporidintegracao', resumo_nota_idintegracao, name='resumo_nota_idintegracao'),
     path('nfe/<str:nota_id>/cce/pdf', baixar_cce_pdf, name='baixar_cce_pdf'),
     path('nfe/<str:nota_id>/cce/xml', baixar_cce_xml, name='baixar_cce_xml'),

     path('nfe/<str:nota_id>/cancelamento/status', consultar_cancelamento_status_nota, name='consultar_cancelamento_status_nota'),
     path('nfe/<str:nota_id>/cancelamento/xml', baixar_xml_cancelamento, name='baixar_xml_cancelamento'),
     
     path('nfe/pdf', baixar_pdf, name='baixar_pdf'),
     path('nfe/xml', baixar_xml, name='baixar_xml'),
     path('nfe/<str:nota_id>/pdf', baixar_pdf, name='baixar_pdf'),
     path('nfe/<str:nota_id>/xml', baixar_xml, name='baixar_xml'),


     # path('configuracao_sistema/', configuracao_sistema_list, name='configuracao_sistema_list'),
     # path('configuracao_sistema/adicionar/', adicionar_configuracao_sistema, name='adicionar_configuracao_sistema'),
     # path('configuracao_sistema/editar/<int:pk>/', editar_configuracao_sistema, name='editar_configuracao_sistema'),
     # path('configuracao_sistema/deletar/<int:pk>/', deletar_configuracao_sistema, name='deletar_configuracao_sistema'),

     # path('api_request/', api_request_view, name='api_request'),
]

Cliente/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=8)
    
    def __str__(self):
        return f"{self.nome}"

produtos/views.py
import logging
import logging.config
import secrets
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from services.Notas_service import NotasService
from .forms import *
from django.forms import formset_factory
from .models import *
from .utils import *
from .fields import *
from django.core.paginator import Paginator
from django.core.cache import cache
from django.contrib.auth.decorators import  login_required, permission_required
from django.http import HttpResponse, Http404

Qtd = 20




def set_list_value_in_cache(list):
    # Verifica se o valor 'list' está na URL e o define no cache
    list_value = list
    if list_value:
        cache.set('list_value', list_value, timeout=300)  # O timeout é em segundos

def get_list_value_from_cache():
    # Obtém o valor de 'list' do cache, se não estiver disponível, usa um valor padrão
    return cache.get('list_value', '20')


def api_request_GET(request):
    # Exemplo de URL e parâmetros (ajuste conforme necessário)
    api_url = 'https://jsonplaceholder.typicode.com/posts'
    api_method = 'GET'
    api_headers = {'Authorization': 'Bearer SEU_TOKEN'}
    api_params = {'parametro1': 'valor1', 'parametro2': 'valor2'}

    # Faz a requisição à API usando a função genérica
    response = make_api_request(api_url, method=api_method, headers=api_headers, params=api_params)

    # Renderiza um template com a resposta da API
    return render(request, 'api_response.html', {'api_response': response})

def api_request_POST(request):
    # Exemplo de URL e parâmetros (ajuste conforme necessário)
    api_url = 'https://jsonplaceholder.typicode.com/posts'
    api_method = 'POST'
    api_headers = {'Authorization': 'Bearer SEU_TOKEN'}
    api_params = {'parametro1': 'valor1', 'parametro2': 'valor2'}

    # Faz a requisição à API usando a função genérica
    response = make_api_request(api_url, method=api_method, headers=api_headers, params=api_params)

    # Renderiza um template com a resposta da API
    return render(request, 'api_response.html', {'api_response': response})

def api_request_PUT(request):
    # Exemplo de URL e parâmetros (ajuste conforme necessário)
    api_url = 'https://jsonplaceholder.typicode.com/posts'
    api_method = 'PUT'
    api_headers = {'Authorization': 'Bearer SEU_TOKEN'}
    api_params = {'parametro1': 'valor1', 'parametro2': 'valor2'}

    # Faz a requisição à API usando a função genérica
    response = make_api_request(api_url, method=api_method, headers=api_headers, params=api_params)

    # Renderiza um template com a resposta da API
    return render(request, 'api_response.html', {'api_response': response})

def api_request_PATCH(request):
    # Exemplo de URL e parâmetros (ajuste conforme necessário)
    api_url = 'https://jsonplaceholder.typicode.com/posts'
    api_method = 'PATCH'
    api_headers = {'Authorization': 'Bearer SEU_TOKEN'}
    api_params = {'parametro1': 'valor1', 'parametro2': 'valor2'}

    # Faz a requisição à API usando a função genérica
    response = make_api_request(api_url, method=api_method, headers=api_headers, params=api_params)

    # Renderiza um template com a resposta da API
    return render(request, 'api_response.html', {'api_response': response})

def api_request_DELETE(request):
    # Exemplo de URL e parâmetros (ajuste conforme necessário)
    api_url = 'https://jsonplaceholder.typicode.com/posts'
    api_method = 'DELETE'
    api_headers = {'Authorization': 'Bearer SEU_TOKEN'}
    api_params = {'parametro1': 'valor1', 'parametro2': 'valor2'}

    # Faz a requisição à API usando a função genérica
    response = make_api_request(api_url, method=api_method, headers=api_headers, params=api_params)

    # Renderiza um template com a resposta da API
    return render(request, 'api_response.html', {'api_response': response})

@login_required
def dashboard(request):
    user_profiles = UserProfile.objects.filter(user=request.user)

    # Verifique se o queryset está vazio
    if user_profiles.exists():
        UserProfiles = user_profiles.first()
    else:
        UserProfiles = None 
        
    context = {
        'UserProfiles': UserProfiles,
    }
    return render(request, 'dashboard.html', context)

@permission_required('produtos.view_produto',raise_exception=True)
@login_required
def produto_list(request):
    
    if request.GET.get("list") and request.GET.get("list").isdigit():
        set_list_value_in_cache(int(request.GET.get("list")))
        Qtlist = 20

        return redirect('lista_produtos')
    
    else:
        Qtlist = get_list_value_from_cache()
    
    

    model_list = Produto.objects.all()
    paginator = Paginator(model_list, Qtlist) 
    

    user_profiles = UserProfile.objects.filter(user=request.user)

    # Verifique se o queryset está vazio
    if user_profiles.exists():
        UserProfiles = user_profiles.first()
    else:
        UserProfiles = None 


    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'UserProfiles': UserProfiles,
        'model_name': 'Produtos',
        'object_list': page_obj,
        'ActionAdd': ListAction(url_name='produto_create', label='Adicionar Produto', icon='fa fa-plus', cor='w3-green'),
        'list_actions': [
            ListAction(url_name='produto_edit', label='Atualizar', icon='fa fa-edit', cor='w3-blue'),
            ListAction(url_name='produto_delete', label='Excluir', icon='fa fa-trash', cor='w3-red'),
        ],
        'column_titles' : [f.name for f in Produto._meta.fields],
        'get_attribute': get_attribute,
    }
    return render(request, 'generico/base_list.html', context)

@login_required
@permission_required('produtos.add_produto',raise_exception=True)
def produto_create(request):
        if request.method == 'POST' :
            try:    
                form = ProdutoForm(request.POST, request.FILES)
                if form.is_valid():
                    try:
                        form.save()
                        messages.success(request, "Atualização realizada com sucesso!")
                        return redirect('lista_produtos')
                            
                    except Exception as e:
                        messages.warning(request, "Erro ao validar dados, por favor preencha corretamente ou tente novamente mais tarde!")
                        return redirect('lista_produtos')
            except Exception as e:
                messages.warning(request, "Erro por favor tente novamente mais tarde!")
                return redirect('lista_produtos')
        else:
            form = ProdutoForm()
        
            user_profiles = UserProfile.objects.filter(user=request.user)

            # Verifique se o queryset está vazio
            if user_profiles.exists():
                UserProfiles = user_profiles.first()
            else:
                UserProfiles = None

            context = {
                'form': form,
                'UserProfiles': UserProfiles,
                'model_name':'Cadastro de Produto',
                'ActionCancel': 'lista_produtos',
                'fieldName' : [
                    ListAction(id=2,url_name='Categoria_list', name='categoria', label='Visualizar', icon='fa fa-edit', cor='w3-blue'), 
                    ListAction(id=4,url_name='Marca_list', name='marca', label='Visualizar', icon='fa fa-edit', cor='w3-blue'),  
                    ListAction(id=6,url_name='Unidade_list', name='unidade', label='Visualizar', icon='fa fa-edit', cor='w3-blue'),
                ],
            }

            return render(request, 'generico/form.html', context)


@login_required
@permission_required('produtos.change_produto',raise_exception=True)
def produto_edit(request, pk):
        produto = get_object_or_404(Produto, pk=pk)
        if request.method == 'POST':
            try:
                form = ProdutoForm(request.POST, request.FILES, instance=produto)
                if form.is_valid():
                    try:
                        form.save()
                        messages.success(request, "Atualização realizada com sucesso!")

                        return redirect('lista_produtos')
                                
                    except Exception as e:
                        messages.warning(request, "Erro ao validar dados, por favor preencha corretamente ou tente novamente mais tarde!")
                        return redirect('lista_produtos')
            except Exception as e:
                messages.warning(request, "Erro por favor tente novamente mais tarde!")
            return redirect('lista_produtos')
        else:
            form = ProdutoForm(instance=produto)
            
            user_profiles = UserProfile.objects.filter(user=request.user)

            # Verifique se o queryset está vazio
            if user_profiles.exists():
                UserProfiles = user_profiles.first()
            else:
                UserProfiles = None

            context = {
                'form': form,
                'UserProfiles': UserProfiles,
                'model_name':'Atualizar Produto',
                'ActionCancel': 'lista_produtos',
                'fieldName' : [  
                    ListAction(id=2,url_name='Categoria_list', name='categoria', label='Visualizar', icon='fa fa-search', cor='w3-blue'),  
                    ListAction(id=4,url_name='Marca_list', name='marca', label='visualizar', icon='fa fa-search', cor='w3-blue'),    
                    ListAction(id=6,url_name='Unidade_list', name='unidade', label='visualizar', icon='fa fa-search', cor='w3-blue'),
                ],
            }

            return render(request, 'generico/form.html', context)

@login_required
@permission_required('produtos.delete_produto',raise_exception=True)
def produto_delete(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    if request.method == 'POST':

produtos/templates/generico/base_list.html
{% extends 'base_teste.html' %}

{% block content %}
{% load custom_filters %}

    {% if ActionAdd and not object_list %}
        <div class="card-title">
            <a class="btn" href="{% url ActionAdd.url_name %}" title=" {{ ActionAdd.label }}">
                <i class="{{ ActionAdd.icon }}"></i>
            </a>
        </div>
    {% endif %}
    
    {% if object_list %}

    
    <div class="card">
        <div class="card-header">
            
            {% if ActionAdd %}
            <div class="card-title">
                {% if perms.Cliente.add_cliente %}
                <a class="btn" href="{% url ActionAdd.url_name %}" title=" {{ ActionAdd.label }}">
                    <i class="{{ ActionAdd.icon }}"></i>
                </a>
                {% endif %}
                <select class="btn" onchange="window.location.href = '?list=' + this.value">
                    <option>Quantidade por pagina</option>
                    <option value="1">1 por pagina</option>
                    <option value="10">10 por pagina</option>
                    <option value="20">20 por pagina</option>
                    <option value="40">40 por pagina</option>
                    <option value="60">60 por pagina</option>
                    <option value="80">80 por pagina</option>
                    <option value="100">100 por pagina</option>
                </select>
            </div>
            {% endif %}

            
          <div class="card-tools">
            
            <ul class="pagination pagination-sm float-right">
                {% if object_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;&laquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}">&laquo;</a></li>
                {% endif %}
              
                {% for num in object_list.paginator.page_range %}
                    {% if object_list.number == num %}
                        <li class="page-item"><a class="page-link" href="#"><strong>{{ num }}</strong></a></li>
                    {% elif num > object_list.number|add:'-5' and num < object_list.number|add:'5' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    
                {% endfor %}
              
                {% if object_list.has_next %}
                
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.paginator.num_pages }}">&raquo;&raquo;</a></li>
                {% endif %}
            </ul>
          </div>

        </div>
        <!-- /.card-header -->
        <div class="card-body p-0" style="overflow-x:auto;">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    {% for field in column_titles %}
                    {% if field == 'descricao' %}
                    
                    {% else %}
                    <th>{{ field }}</th>
                    {% endif %}
                    {% endfor %}
                    <th colspan="2">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}


                <tr>
                    {% for column_title in column_titles %}
                    {% if column_title == 'descricao' %}

                    {% else %}
                    <td>
                        {% if column_title == 'imagem' %}
                        <img src="/media/{{ object|get_attribute:column_title }}" width="50" alt="Imagem do produto">
                        {% else %}
                        {{ object|get_attribute:column_title|truncatewords:50 }}
                        {% endif %}
                    </td>
                    {% endif %}
                    {% endfor %}

                    {% for action in list_actions %}
                    {% if action %}
                    <td>
                        <a href="{% url action.url_name object.id %}" title="{{action.label}}">
                            {% if action.icon %}
                            <i class="{{action.icon}}"></i>
                            {% endif %}
                        </a>
                    </td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                {% if object_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;&laquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}">&laquo;</a></li>
                {% endif %}
              
                {% for num in object_list.paginator.page_range %}
                    {% if object_list.number == num %}
                        <li class="page-item"><a class="page-link" href="#"><strong>{{ num }}</strong></a></li>
                    {% elif num > object_list.number|add:'-5' and num < object_list.number|add:'5' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    
                {% endfor %}
              
                {% if object_list.has_next %}
                
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ object_list.paginator.num_pages }}">&raquo;&raquo;</a></li>
                {% endif %}
            </ul>
          </div>
          
        

    {% else %}
    <hr>
    <p style="text-align: center;">Nenhum registro encontrado.</p>
    <hr>
    {% endif %}


{% endblock %}

produtos/templates/generico/form.html
{% extends 'base_teste.html' %}

{% block content %}
{% load custom_filters %}

<style>
    .form-group {
        display: inline-block;
        width: 30%;
        /* Define a largura de cada campo */
        margin-right: 2%;
        /* Adiciona um espaço entre os campos */
    }
</style>

<!-- jquery validation -->
<div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ model_name }}</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form id="quickForm" action="" method="POST" enctype="multipart/form-data">
        <div class="card-body">
            {% csrf_token %}
            {% for field in form %}
            {% if field.label != 'Descricao' %}
            <div class="form-group">
            {% else%}
            
            {% endif %}
                    
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>

                {% for action in fieldName %}
                    {% if field.name == action.name %}
                    {% if action %}
                    <a class="btn btn-outline-secondary" style="margin: 5px; font-size: 10px; " {% if not action.formGen %}
                        onclick="myFunction('{% url action.url_name %}');" {% else %} data-bs-toggle="offcanvas"
                        data-bs-target="#OpenModal{{ action.id }}" {% endif %}>
                        {{ action.label }}
                    </a>
                    {% endif %}
                    {% endif %}
                {% endfor %}

                {% if field.widget.input_type != 'checkbox' %}
                {{ field }}
                <script>
                    document.getElementById("{{ field.id_for_label }}").classList.add("form-control");
                </script>
                {% else %}
                {{ field }}
                {% endif %}
            </div>
            {% if field.label == 'Imagem' %}
        </div>
        <div class="card-body">
            {% endif %}
            {% if forloop.counter|divisibleby:3 and field.label != 'Descricao' %}
            <!-- Fecha a linha a cada 3 campos, exceto para o campo de descrição -->
        </div>
        <div class="card-body">
            {% endif %}
            {% endfor %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Confirmar</button>
        </div>
    </form>
</div>

<script>
    function myFunction(url) {
        window.open(url, "_blank", "toolbar=yes, scrollbars=yes, resizable=yes, top=1, left=1, width=800, height=600");
    }
</script>

{% endblock %}

produtos/templates/generico/form_delete.html
{% extends 'base_teste.html' %}

{% block content %}

<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Tem certeza que deseja deletar {{ delete }}?</p>

    <br>
    <div class="form-group">
      <button type="submit" class="btn btn-danger">Deletar</button>
      <a href="{% url ActionCancel %}" class="btn btn-success">Voltar</a>
    </div>
  </form>
</div>

{% endblock %}