Cliente/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     
     path('', Cliente_list.as_view(), name='Cliente_list'),
     path('create', Cliente_create.as_view(), name='Cliente_create'),
     path('edit/<int:pk>', Cliente_edit.as_view(), name='Cliente_edit'),
     path('delete/<int:pk>', Cliente_delete.as_view(), name='Cliente_delete'),

     path('sem-permissao/', sem_permissao, name='sem_permissao'),

     # path('api_request/', api_request_view, name='api_request'),
] 

integra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produtos.urls')),
    path('clientes/', include('Cliente.urls')),
    path('funcionario/', include('Funcionario.urls')),
    path('fornecedor/', include('Fornecedor.urls')),
    path('configuracao/', include('configuracao.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

Cliente/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=8)
    
    def __str__(self):
        return f"{self.nome}"

Fornecedor/models.py
from django.db import models

# Create your models here.
class Fornecedor(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=8)

    class Meta:
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
    
    def __str__(self):
        return f"{self.nome}"

Funcionario/models.py
from django.db import models

# Create your models here.
class Funcionario(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=8)
    
    class Meta:
        verbose_name = 'Funcionario'
        verbose_name_plural = 'Funcionarios'
    
    def __str__(self):
        return f"{self.nome}"

produtos/models.py
from django.contrib.auth.models import User
from django.db import models

from Fornecedor.models import Fornecedor

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    imagem = models.ImageField(upload_to='user_image/', default='user_image/img_avatar1.png', null=True, blank=True)

class Produto(models.Model):
    imagem = models.ImageField(upload_to='produtos/')
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    marca = models.ForeignKey('Marca', on_delete=models.CASCADE)
    unidade = models.ForeignKey('Unidade', on_delete=models.CASCADE)
    estoque_minimo = models.IntegerField()
    estoque_maximo = models.IntegerField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    

    def __str__(self):
        return f"{self.nome}"

class Categoria(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField()

    def __str__(self):
        return f"{self.nome}"

class Marca(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField()

    def __str__(self):
        return f"{self.nome}"

class Promocao(models.Model):
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE)
    data_inicio = models.DateField()
    data_fim = models.DateField()
    desconto = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.produto} - Desconto: {self.desconto}%"

class Unidade(models.Model):
    nome = models.CharField(max_length=10)
    
    def __str__(self):
        return f"{self.nome}"

# class Cliente(models.Model):
#     nome = models.CharField(max_length=255)
#     email = models.EmailField()
#     telefone = models.CharField(max_length=20)
#     endereco = models.CharField(max_length=255)
#     cidade = models.CharField(max_length=255)
#     estado = models.CharField(max_length=2)
#     cep = models.CharField(max_length=8)
    
#     def __str__(self):
#         return f"{self.nome}"

# class Fornecedor(models.Model):
#     nome = models.CharField(max_length=255)
#     email = models.EmailField()
#     telefone = models.CharField(max_length=20)
#     endereco = models.CharField(max_length=255)
#     cidade = models.CharField(max_length=255)
#     estado = models.CharField(max_length=2)
#     cep = models.CharField(max_length=8)

#     class Meta:
#         verbose_name = 'Fornecedor'
#         verbose_name_plural = 'Fornecedores'
    
#     def __str__(self):
#         return f"{self.nome}"

# class Funcionario(models.Model):
#     nome = models.CharField(max_length=255)
#     email = models.EmailField()
#     telefone = models.CharField(max_length=20)
#     endereco = models.CharField(max_length=255)
#     cidade = models.CharField(max_length=255)
#     estado = models.CharField(max_length=2)
#     cep = models.CharField(max_length=8)
    
#     class Meta:
#         verbose_name = 'Funcionario'
#         verbose_name_plural = 'Funcionarios'
    
#     def __str__(self):
#         return f"{self.nome}"

class Localizacao(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    
    class Meta:
        verbose_name = 'Localização'
        verbose_name_plural = 'Localizações'
    
    def __str__(self):
        return f"{self.nome}"

class OrdemCompra(models.Model):
    fornecedor = models.ForeignKey('Fornecedor.Fornecedor', on_delete=models.CASCADE)
    produtos = models.ManyToManyField('Produto', through='ItemOrdemCompra')
    data_emissao = models.DateField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Ordem de Compra'
        verbose_name_plural = 'Ordens de Compra'
    
    def __str__(self):
        return f"{self.fornecedor}"+" - "+f"{self.data_emissao}"+" - R$"+f"{self.total}"


class ItemOrdemCompra(models.Model):
    ordem_compra = models.ForeignKey('OrdemCompra', on_delete=models.CASCADE, null=False, blank=False)
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE, null=False, blank=False)
    quantidade = models.IntegerField(null=False, blank=False)
    preco_unitario = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)

    class Meta:
        verbose_name = 'Item Ordem de Compra'
        verbose_name_plural = 'Itens Ordem de Compra'
    
    def __str__(self):
        return f"{self.produto}"

class OrdemVenda(models.Model):
    cliente = models.ForeignKey('Cliente.Cliente', on_delete=models.CASCADE)
    produtos = models.ManyToManyField('Produto', through='ItemOrdemVenda')
    data_emissao = models.DateField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Ordem de Venda'
        verbose_name_plural = 'Ordens de Venda'
    
    def __str__(self):
        return f"{self.cliente}"+" - "+f"{self.data_emissao}"

class ItemOrdemVenda(models.Model):
    ordem_venda = models.ForeignKey('OrdemVenda', on_delete=models.CASCADE)
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    preco_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Item Ordem de Venda'
        verbose_name_plural = 'Itens Ordem de Venda'
    
    def __str__(self):
        return f"{self.produto}"

class ConfiguracaoSistema(models.Model):
    informacoes_contato = models.TextField(verbose_name='Informação de contato', help_text='Informação de contato')
    termos_de_uso = models.TextField(verbose_name='Termo de uso', help_text='Termo de uso')
    politicas_privacidade = models.TextField(verbose_name='Politica privacidade', help_text='Politica privacidade')

    class Meta:
        verbose_name = 'Configuração de Sistema'
        verbose_name_plural = 'Configurações de Sistema'
    
    def __str__(self):
        return f"{self.informacoes_contato}"

templates/dashboard.html
{% extends 'base_teste.html' %}

{% block content %}

<div class="row">

    {% if perms.produtos.view_funcionario %}
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box" style="background-color: #5793d8; color: #ffffff;">
        <div class="inner">
          <h3>Funcionários</h3>

          <p>&nbsp;</p>
        </div>
        <div class="icon">
          <i class="fas fa-user-tie"></i>
        </div>
        <a href="{% url 'Funcionario_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    {% endif %}
    <!-- ./col -->
    {% if perms.produtos.view_fornecedor %}
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box" style="background-color: #0d5c81; color: #ffffff;">
        <div class="inner">
          <h3>Fornecedores</h3>

          <p>&nbsp;</p>
        </div>
        <div class="icon">
          <i class="fas fa-people-carry"></i>
        </div>
        <a href="{% url 'Fornecedor_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    {% endif %}
    <!-- ./col -->
    {% if perms.Cliente.view_cliente %}
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box" style="background-color: #17abf0; color: #ffffff;">
        <div class="inner">
          <h3>Clientes</h3>

          <p>&nbsp;</p>
        </div>
        <div class="icon">
          <i class="fas fa-users"></i>
        </div>
        <a href="{% url 'Cliente_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    {% endif %}
    <!-- ./col -->
    {% if perms.produtos.view_produto %}
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box" style="background-color: #478eaf; color: #ffffff;">
        <div class="inner">
          <h3>Produtos</h3>

          <p>&nbsp;</p>
        </div>
        <div class="icon">
          <i class="fa fa-shopping-cart"></i>
        </div>
        <a href="{% url 'lista_produtos' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    {% endif %}
    <!-- ./col -->
    {% if perms.produtos.view_ordemcompra %}

    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #2890af; color: #ffffff;">
          <div class="inner">
            <h3>Ordens de Compras</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-pallet"></i>
          </div>
          <a href="{% url 'ordem_compra_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      <!-- ./col -->
      {% if perms.produtos.view_ordemvenda %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #164ea1; color: #ffffff;">
          <div class="inner">
            <h3>Ordens de Vendas</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-dolly-flatbed"></i>
          </div>
          <a href="{% url 'ordem_venda_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      <!-- ./col -->
      {% if perms.produtos.view_configuracaosistema %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #4283a1; color: #ffffff;">
          <div class="inner">
            <h3>Configurações</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-cogs"></i>
          </div>
          <a href="{% url 'configuracao_sistema_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      <!-- ./col -->
      {% if perms.produtos.view_promocao %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #4283a1; color: #ffffff;">
          <div class="inner">
            <h3>Promoção</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-hand-holding-usd"></i>
          </div>
          <a href="{% url 'Promocao_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      <!-- ./col -->
      {% if perms.produtos.view_categoria %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #4283a1; color: #ffffff;">
          <div class="inner">
            <h3>Categorias</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-stream"></i>
          </div>
          <a href="{% url 'Categoria_list' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}

      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box" style="background-color: #4283a1; color: #ffffff;">
          <div class="inner">
            <h3>Nota Fiscal</h3>
  
            <p>&nbsp;</p>
          </div>
          <div class="icon">
            <i class="fas fa-stream"></i>
          </div>
          <a href="{% url 'home_notas' %}" class="small-box-footer">Mais Informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      
  </div>


{% endblock %}